import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

const StoryPart = ({ children, author, color, editing }) => {
  return (
    <span
      className={`${styles.part} ${editing ? styles.editing : ''}`}
      contentEditable={editing}
    >
      {children}
      <span className={styles.author}>{author}</span>
    </span>
  );
};

const getARandomLightColor = () => {
  const letters = '0123456789ABCDEF';
  let color = '#';
  for (let i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)];
  }
  return color;
};

const PARTS = [
  {
    id: 1,
    author: 'Jack White',
    text: 'Once upon a time, there was a painter named "P".',
    color: getARandomLightColor(),
  },
  {
    id: 2,
    author: 'Charles Dickens',
    text: 'P was a very talented painter, but he was also very lazy.',
    color: getARandomLightColor(),
  },
  {
    id: 3,
    author: 'Charles Bukowski',
    text: 'P was so lazy that he would rather sleep than paint.',
    color: getARandomLightColor(),
  },
  {
    id: 4,
    author: 'Alber Camus',
    text: 'One day, P was sleeping in his bed when he heard a knock on the door.',
    color: getARandomLightColor(),
  },
  {
    id: 5,
    author: 'Rachel Carson',
    text: 'P opened the door and saw, ',
    color: getARandomLightColor(),
  },
  {
    id: 6,
    author: 'Virginia Woolf',
    text: 'a beautiful',
    color: getARandomLightColor(),
  },
  {
    id: 7,
    author: 'Leo Tolstoy',
    text: 'box, wrapped in some old newspapers.',
    color: getARandomLightColor(),
  },
];

export default function Home() {
  const [parts, setParts] = useState(PARTS);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.story}>
        <h1 className={styles.title}>
          <StoryPart>A painter called P</StoryPart>
        </h1>

        <div className={styles.body}>
          {parts.map((part, index) => (
            <>
              <StoryPart key={part.id} author={part.author} color={part.color}>
                {part.text}
              </StoryPart>
              <span
                className={`${styles.addPart} ${
                  index === parts.length - 1 ? styles.visible : ''
                }`}
                onClick={() => {
                  setParts([
                    ...parts,
                    {
                      id: parts.length + 1,
                      editing: true,
                      author: 'Anonymous',
                    },
                  ]);
                }}
              >
                +
              </span>
            </>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://github.com/thevahidal/novel'
          target='_blank'
          rel='noopener noreferrer'
        >
          Github
        </a>
      </footer>
    </div>
  );
}
